alexa/ask-cli

README.md
Adds the following to the `README`:
1. Add title
2. Bold formatting for "Getting Started" steps
=> Add README title and formatting for getting started steps

package.json
Added pre-commit hook to run eslint before every commit
Updated husky version
**Please run `npm i husky --save-dev` to install the hook**
=> Eslint precommit hook

docs/concepts/Alexa-Skill-Project-Definition.md, docs/concepts/Deploy-Command.md
Solve https://github.com/alexa-labs/ask-cli/issues/41 by adding the docs
=> docs: add concepts for project definition and deploy command

docs/concepts/Configure-Command.md
This PR adds documentation for v2 configure command.
=> docs: add concepts for configure command

lib/model/dialog-replay-file.js, test/unit/model/dialog-replay-file-test.js
Fixing the test failures from the last release.
=> test: fix the test failure from the prior release

lib/clients/git-client.js, lib/commands/v2new/hosted-skill-helper.js, test/unit/clients/git-client-test.js, test/unit/commands/util/upgrade-project/helper-test.js, test/unit/commands/util/upgrade-project/hosted-skill-helper-test.js, test/unit/commands/util/upgrade-project/ui-test.js, test/unit/commands/v2new/hosted-skill-helper-test.js
fix: import URL object & handle cross-platform file separator
=> fix: import URL object & handle cross-platform file separator

CHANGELOG.md, docs/concepts/Dialog-Command.md, package.json
Adding documentation for Dialog command V2. Related [commit](https://github.com/alexa-labs/ask-cli/commit/c88938cc2054645162f16d0e0bc6c7085b96cd5f).
=> docs: add concepts for dialog command

test/unit/commands/util/upgrade-project/index-test.js
npm test
check to make sure on the same branch
git status
=> fix: fix issue when test was switching git branch to master

docs/concepts/Init-Command.md
Adding documentation for Init command.
=> docs: add init command documentation

lib/commands/smapi/cli-customization-processor.js
=> fix: fix issues when parent parameter is not camel case

bin/askx-smapi.js
Change to show the error message from smapi-sdk request
=> fix: show error for the smapi commands from the upstream request

docs/concepts/New-Command.md
=> Create Ask New Command documentation

lib/commands/v2new/ui.js
=> fix: askx new -> list of selections is not static when choosing deployer

.travis.yml
Removing 
npm install -g
from travis.yml
=> chore: travis config clean up

lib/clients/git-client.js, lib/commands/util/upgrade-project/hosted-skill-helper.js, test/unit/clients/git-client-test.js, test/unit/commands/util/upgrade-project/hosted-skill-helper-test.js
=> fix: ashx new AHS -> fails with credential problem

lib/commands/util/upgrade-project/hosted-skill-helper.js, test/unit/commands/util/upgrade-project/hosted-skill-helper-test.js
In checkIfDevBranchClean method, we check three things before executing upgrade-project:
1) are all changes committed?
2) does the count of commit difference between dev and origin/dev equal zero?
3) Is the count of commit difference between dev and master equal zero?
=> askx upgrade-project -> remove skill.json and other v1 artifacts

lib/builtins/deploy-delegates/cfn-deployer/index.js, lib/builtins/deploy-delegates/lambda-deployer/index.js, lib/commands/v2new/helper.js, lib/commands/v2new/ui.js, lib/controllers/skill-infrastructure-controller/deploy-delegate.js, lib/utils/constants.js, test/unit/commands/v2new/helper-test.js, test/unit/commands/v2new/ui-test.js
* feat: skip bootstrap if template is deployer-aware and use deployer specific template for each language
* fix: improve message of askx new command
=> feat: askx new -> support deployer-aware project in  command an improve UI

lib/commands/smapi/customizations/parameters.json
add skipUnwrap to 2 new complex body parameters
=> fix: add skipUnwrap to 2 new complex body parameters

.gitignore, README.md, lib/commands/init/helper.js, lib/controllers/authorization-controller/index.js, lib/controllers/authorization-controller/messages.js, package.json, test/unit/controller/authorization-controller/index-test.js
It will be having consistent UX to confirm user's login, similar to this one https://ask-cli-static-content.s3-us-west-2.amazonaws.com/html/ask-cli-no-browser.html
=> fix: improve user experiences by updating the post-lwa response webpage

lib/commands/new/helper.js, lib/commands/new/ui.js, lib/commands/new/wizard-helper.js, test/unit/commands/new/helper-test.js, test/unit/commands/new/ui-test.js, test/unit/commands/new/wizard-helper-test.js
https://github.com/alexa/ask-cli/issues/115
=> fix: creating a new self-hosted skill fails with TypeError

lib/builtins/build-flows/python-pip/build.ps1
This commit fixes https://github.com/alexa/ask-cli/issues/123 by updating the python-pip flow for Windows Powershell script.
=> fix: update python-pip build-flow's build powershell script

lib/commands/abstract-command.js, lib/commands/util/git-credentials-helper/index.js, test/unit/commands/util/git-credentials-helper/index-test.js
This fix the issue mentioned in https://github.com/alexa/ask-cli/issues/128
=> fix: treat unrecognized command separately from command.handle method

lib/commands/smapi/smapi-command-handler.js, package.json, test/unit/commands/smapi/smapi-command-handler-test.js
support configuring smapi and lwa endpoint using env variables
=> feat: support custom smapi and lwa endpoint based on env variables

lib/clients/aws-client/s3-client.js, test/unit/clients/aws-client/s3-client-test.js
https://github.com/alexa/ask-cli/issues/140
*Notes:*
- To reproduce this issues, please refer to:
1. Steps to Create a Music or Radio Skill
https://developer.amazon.com/en-US/docs/alexa/music-skills/steps-to-create-a-music-skill.html
2. Steps to create and manage catalogs
https://developer.amazon.com/en-US/docs/alexa/music-skills/upload-catalogs.html#steps-to-create-and-manage-catalogs
=> Upload catalog fix

docs/concepts/Deploy-Command.md, lib/commands/deploy/helper.js, lib/commands/deploy/index.js, lib/commands/option-model.json, lib/controllers/skill-metadata-controller/index.js, test/unit/commands/deploy/helper-test.js, test/unit/commands/deploy/index-test.js, test/unit/controller/skill-metadata-controller-test.js
add force-deploy flag to deploy command
Issue: https://github.com/alexa/ask-cli/issues/77
=> feat: add force-deploy flag to deploy command

test/unit/utils/string-utils-test.js
This function has no unit test code.
So I've tried to add it.
- kebabCase()
- camelCase()
=> test: add test case on string-utils

lib/commands/smapi/cli-customization-processor.js, test/unit/commands/smapi/cli-customization-processor-test.js
This PR addresses https://github.com/alexa/ask-cli/issues/179.
=> fix: correct the decision of a required field in smapi command generation

lib/commands/abstract-command.js, test/unit/commands/abstract-command-test.js
This fixes the issue mentioned in https://github.com/alexa/ask-cli/issues/178.
=> fix: add the missed profile variable into the runtimeProfile method

lib/builtins/build-flows/nodejs-npm/build.ps1, lib/builtins/build-flows/nodejs-npm/build.sh, lib/builtins/build-flows/python-pip/build.ps1, lib/builtins/build-flows/python-pip/build.sh, lib/controllers/skill-code-controller/code-builder.js, test/unit/controller/code-builder-test.js
Addressing https://github.com/alexa/ask-cli/issues/196
=> fix: adding qoutes to fix issue of zipping folder with spaces

lib/commands/smapi/customizations/parameters.json, package.json, test/integration/commands/smapi-commands-test.js
=> feat: add new smapi commands for asr evaluations

docs/concepts/CI-CD.md
=> docs: add docs about ci/cd

lib/commands/deploy/index.js, lib/commands/util/upgrade-project/helper.js, lib/commands/util/upgrade-project/index.js, package.json, test/unit/commands/util/upgrade-project/helper-test.js, test/unit/commands/util/upgrade-project/index-test.js
Support the upgrade of v1 skill project which is not deployed. Tested with multiple v1 skill templates.
=> feat: support upgrade-project command with un-deployed project

docs/FAQ.md, docs/concepts/Deploy-Command.md
Addressing issue https://github.com/alexa/ask-cli/issues/218
=> docs: add docs how to deploy only skill package

lib/commands/util/git-credentials-helper/index.js, lib/commands/util/upgrade-project/hosted-skill-helper.js, lib/controllers/hosted-skill-controller/clone-flow.js, lib/controllers/hosted-skill-controller/index.js, test/unit/commands/util/git-credentials-helper/index-test.js, test/unit/commands/util/upgrade-project/hosted-skill-helper-test.js, test/unit/controller/hosted-skill-controller/clone-flow-test.js, test/unit/controller/hosted-skill-controller/index-test.js, test/unit/fixture/model/hosted-proj/.ask/ask-states.json
removing state infrastructure info from state file for hosted skills
new states file for hosted skill should be
```
{
"askcliStatesVersion": "2020-03-31",
"profiles": {
"default": {
"skillId": "amzn1.ask.skill.a6767bfd-0692-45c0-af8a-b43d1a0f9ad4"
}
}
}
```
TODO. need to update pre-push hook
=> Git credentials simplify

.github/workflows/integration-test.yml, lib/commands/abstract-command.js, lib/commands/smapi/smapi-command-handler.js, lib/model/abstract-config-file.js, lib/model/app-config.js, lib/model/manifest.js, lib/model/regional-stack-file.js, lib/model/resources-config/ask-resources.js, lib/model/resources-config/ask-states.js, lib/utils/profile-helper.js, test/unit/commands/abstract-command-test.js, test/unit/model/abstract-config-file-test.js, test/unit/model/app-config-test.js
Before writing docs about using env variables for running ask cli in CI/CD, I am fixing support for smapi command to use env variables.
=> fix: add support to run smapi command using env settings

lib/clients/git-client.js, test/unit/clients/git-client-test.js
Addressing https://github.com/alexa/ask-cli/issues/231
=> fix: add qoutes around folder path to fix issue when path has space

lib/commands/new/wizard-helper.js
*Issue #, if available:* The suggested project name does not correspond with skill name when "ask new".
*Description of changes:* Fix suggested project name to skill name.
=> Fix suggested project name to skill name.

lib/commands/new/wizard-helper.js
=> fix: default folder name to skill name for ask new command

lib/commands/new/wizard-helper.js, lib/utils/url-utils.js, test/unit/commands/new/wizard-helper-test.js, test/unit/utils/url-utils-test.js
remove check for template url ending with .git
Addressing https://github.com/alexa/ask-cli/issues/269
and https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/550
=> fix: remove check for template url ending with .git

package.json, test/integration/commands/smapi-commands-test.js
=> feat: update ask smapi model to 1.10.1

.github/workflows/functional-test-clean-up.yml, .github/workflows/functional-test.yml, .github/workflows/integration-test.yml, .github/workflows/unit-test.yml, package.json, scripts/ask-clean-up.js, scripts/aws-clean-up.js, test/functional/commands/high-level-commands-test.js
Adding functional test with Github Actions that runs for every push.
Also adding functional test clean up workflow to remove created aws and ask resources once a day.
Using ubuntu runner for now - we may expand to run on mac os and windows in the future.
=> test: add functional tests to github actions

lib/commands/deploy/index.js
Addressing https://github.com/alexa/ask-cli/issues/280
=> fix: propogate correct error message for file not found

.github/workflows/functional-test.yml, .github/workflows/integration-test.yml, .github/workflows/unit-test.yml, CONTRIBUTING.md
adding contributer guide
https://github.com/alexa/ask-cli/blob/contributer-guide/CONTRIBUTING.md
=> Contributer guide

.github/workflows/integration-test.yml, .github/workflows/unit-test.yml
enable gh actions for PRs to make it work with fork PR's
unable to add for functional tests since developers do not have access to GH secrets.
=> test: test

package.json
Integration test will be fixed after including the patch release from smapi-sdk.
=> fix: bump ask-smapi-sdk version to include some fix to smapi commands

.github/ISSUE_TEMPLATE/issue-report.md
Adding info about Alexa public docs and Amazon developer forum.
=> chore: add more info github issue template

.github/auto-assign-config.yml, .github/workflows/auto-assign.yml
=> chore: add auto assign Github Action

package.json, test/functional/commands/high-level-commands-test.js, test/test-utils.js
adding retry to functional tests
=> test: add retries to functional tests

docs/concepts/Alexa-Skill-Project-Definition.md, docs/concepts/Deploy-Command.md, lib/builtins/deploy-delegates/cfn-deployer/helper.js, lib/builtins/deploy-delegates/cfn-deployer/index.js, lib/exceptions/cli-cfn-deployer-error.js, test/unit/builtins/cfn-deployer/helper-test.js, test/unit/builtins/cfn-deployer/index-test.js, test/unit/run-test.js
full rewrite of CloudFormation Deployer
1) changed to async/await and promises
2) fixed error handling logic (fix issues when no error message is displayed when stack deploy fails)
3) removed is code modified check since it was not working. Correct checking if code is modified should be fixed in https://github.com/alexa/ask-cli/pull/245
4) added custom s3 bucket and key
5) added user provided CloudFormation parameters
6) added user provided CloudFormation capabilities
7) added CloudFormation outputs to .ask/ask-states.json file
**Automated Tests**
```
npm test
npm run functional-test
```
**Some Additional Manual Tests**
1) run deploy on existing skill - should succeed
```
[Warn]: The hash of current skill package folder does …
```
=> feat: rewrite of cf deployer

lib/utils/dynamic-config.js
name of the variable to set custom base url for s3 scripts was incorrect. fixing it.
=> fix: name for variable to configure custom s3 scripts base url

docs/concepts/Deploy-Command.md, docs/concepts/Deployer-CFN-Deployer.md
- small edits for new infrastructure features
- added doc with practical usage examples of CFN-Deployer features
=> docs: Practical usage and examples of CFN-Deployer features

lib/builtins/deploy-delegates/cfn-deployer/index.js
fixing bug when new s3 bucket created on each cf deploy. regression from cf deploy rewrite.
=> fix: new s3 bucket created on each cf deploy

docs/concepts/Deploy-Command.md, docs/concepts/Deployer-CFN-Deployer.md
Minor typos fixed related to the new skillInfrastructure.userConfig properties. 
=> Fixed typos in CFN deployer docs. 

bin/ask-skill.js, bin/ask-util.js, bin/ask.js, lib/clients/http-client.js, lib/commands/new/ui.js, lib/commands/new/wizard-helper.js, lib/commands/skill/add-locales/helper.js, lib/commands/skill/add-locales/index.js, lib/commands/skill/add-locales/ui.js, lib/commands/skill/skill-commander.js, lib/controllers/skill-metadata-controller/index.js, lib/utils/constants.js, test/unit/clients/http-client-test.js, test/unit/commands/new/ui-test.js, test/unit/commands/new/wizard-helper-test.js, test/unit/commands/skill/add-locales/helper-test.js, test/unit/commands/skill/add-locales/index-test.js, test/unit/commands/skill/add-locales/ui-test.js, test/unit/controller/skill-metadata-controller-test.js, test/unit/run-test.js
This may solve the issue from https://github.com/alexa/ask-cli/issues/177
--- 
Examples of usage (assuming only en-AU is set in the project):
```
$ ask skill add-locales
? Please select at least one locale to add: (Press <space> to select, <a> to toggle all, <i> to invert selection)
❯◯ en-AU
◯ de-DE
◯ en-CA
◯ en-GB
◯ en-IN
◯ en-US
◯ es-ES
(Move up and down to reveal more choices)
// after selecting the first four, the terminal will look like =>
? Please select at least one locale to add: en-AU, de-DE, en-CA, en-GB
The following skill locale(s) have been added according to your local project:
Added locale de-DE.json from the template of interactionModel
Added locale en-CA.json from en-AU's interactionModel
Added locale en-GB.json from en-AU's interactionModel
Please check the added files …
```
=> feat: implement "ask skill add-locales" command

lib/view/multi-tasks-view.js, test/unit/clients/aws-client/s3-client-test.js
1) adding tests to increase code coverage
2) removed unreachable code path
My open PR unit tests failed since code coverage under 95% but there are no uncovered lines. Creating this PR, to add few extra tests.
https://github.com/alexa/ask-cli/pull/340
=> Minor clean up

.gitignore, Vagrantfile
Adding vagrant to help us test locally using Ubuntu (possibly windows in the future - need to find windows image that is free to use).
1) Install Virtual Box
2) Install Vagrant https://www.vagrantup.com/downloads
```
vagrant up
vagrant ssh
```
inside of the VM
```
ask -h
```
change some files, the changes should be reflected in the VM right away
=> chore: add vagrant

docs/concepts/Alexa-Hosted-Skill-Commands.md
Adding more documentations
https://github.com/alexa/ask-cli/issues/355
=> docs: add info about hosted skill dev branch

package.json
bump axios version to fix security vulnerability.
=> chore: bump axios version

lib/utils/constants.js
=> Fix Python debugger script location path

package.json
Bump ask-smapi-model to the new version
=> feat: bump ask-smapi-model to v1.17.0

package.json, test/integration/commands/smapi-commands-test.js, test/integration/fixtures/experiment-metric-configuration.json
- feat: bump ask-smapi-model to v1.19.1
=> feat: bump ask-smapi-model to v1.19.1

.github/auto-assign-config.yml, .github/workflows/integration-test.yml, .github/workflows/unit-test.yml, lib/commands/run/index.js, package.json, test/unit/commands/run/index-test.js
- feat: bump ask-smapi-model to v1.19.7 
-  update Github Actions workflows with node 14, 16 versions 
- Bug fix broken unit tests on node v16 versions by checking for null
- 
=> feat: bump ask-smapi-model to v1.19.7 and update Github Actions
