alexa/ask-cli

lib/commands/deploy/helper.js
lib/commands/deploy/index.js
lib/controllers/skill-metadata-controller/index.js
lib/utils/constants.js
test/unit/commands/deploy/helper-test.js
test/unit/commands/deploy/index-test.js
test/unit/controller/skill-metadata-controller-test.js

NA
Add enable skill logic to ask deploy, when deploying resources finished, cli will call smapi to enable skill

feat: enable skill after deploy resources finished

---

.commitlintrc.json
CHANGELOG
README.md
package.json

Enforce conventional commit by adding commitlint and standard-version to uniform the commit messages and the release flow.
Future flow of releasing will be 
1. **git commit**. Triggers the husky hook "commit-msg", which will check if commit messages comply the conventional commit rules. 
2. **npm run pre-release**. This will commit changelog changes and bump the version.
3. **git push --follow-tags origin master && npm publish**. Triggers husky hook "pre-push", which will make sure to run tests before push, release tags and publish to NPM.
***Note:*** This change also removes the changelog file and revert the version bump, as the release didn't happen. We will be using standard-version to manage the pre-release work.
By submitting this pull request, I confirm that you can use, modify, …

chore: enforce conventional commit by introducing commitlint and standard-version

---

bin/askx-smapi.js

New message should look like 
[Warn]: Blabla
instead of
[Fatal]: Blabla
Test
askx smapi get-skill-status -s xxx

fix: change from fatal to warn message

---

lib/commands/smapi/smapi-commander.js

Adding -p shortcut to --profile flag
Adding description for debug and profile flags.
Description came from https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-command-reference.html

fix: adding -p shortcut and description for default options

---

lib/commands/smapi/cli-customization-processor.js
lib/commands/smapi/customizations/hook-functions/append-vendor-id.js
lib/commands/smapi/customizations/parameters.json
test/unit/commands/smapi/cli-customization-processor-test.js
test/unit/commands/smapi/hook-functions/append-vendor-id-test.js

fix issue of vendor-id being required parameter

fix: fix issue of vendor-id being required parameter

---

lib/commands/configure/aws-profile-setup-helper.js
lib/commands/configure/helper.js
lib/commands/configure/messages.js
lib/commands/v2new/hosted-skill-helper.js
lib/controllers/authorization-controller/index.js
lib/utils/constants.js
package.json
test/unit/commands/configure/aws-profile-setup-helper-test.js
test/unit/commands/configure/helper-test.js
test/unit/commands/v2new/hosted-skill-helper-test.js
test/unit/controller/authorization-controller/index-test.js

* Add warn messaging to inform user to keep authorization code, access tokens and AWS secret key and access key id safe.
* Update "opn" to "open" package.

fix: update to "open" package and add warn messaging for token security

---

docs/concepts/Dialog-Command.md
lib/commands/dialog/index.js
lib/commands/dialog/replay-mode.js
lib/controllers/dialog-controller/index.js
test/unit/commands/dialog/index-test.js
test/unit/controller/dialog-controller/index-test.js

append quit to replay file, update messaging, continue session after recording
* enable interaction after record args validation failure.
* option to append .quit to replay file.
* Update messaging when command is executed outside cli project.
* session persistence once record is done.

feat: enable interaction after record args validation failure, option to

---

lib/commands/configure/aws-profile-setup-helper.js
lib/commands/configure/index.js
lib/utils/constants.js
test/unit/commands/configure/aws-profile-setup-helper-test.js

.ask/cli_config
.aws/credentials
BEFORE
-rw-r--r--@ 
AFTER
-rw-------

fix: file permissions for .ask/cli_config and .aws/credentials

---

lib/commands/dialog/interactive-mode.js
lib/commands/dialog/replay-mode.js
lib/commands/option-model.json
lib/commands/v2new/index.js
test/unit/commands/dialog/replay-mode-test.js
test/unit/commands/v2new/index-test.js

* Update headers in dialog command to display the usage of `.record` and `.quit` sub commands.
* Provide messaging for the usage of git for Hosted skill after clone finishes.
* Provide better description for ASK CLI profile.

fix: update messaging in dialog, configure and new commands

---

docs/concepts/Alexa-Hosted-Skill-Commands.md
docs/concepts/New-Command.md
lib/commands/smapi/customizations/parameters.json
lib/commands/v2new/ui.js
lib/utils/constants.js
test/unit/commands/v2new/ui-test.js

fix: askx new -> change the representation layer for deployers

---

lib/commands/abstract-command.js
lib/utils/constants.js
test/functional/commands/api/index.js
test/unit/commands/abstract-command-test.js

Minor version update:
```
##########################################################################
[Info]: New MINOR version (v0.12.0) of ask-cli-x is available now. Current version v0.2.0.
It is recommended to use the latest version. Please update using "npm upgrade -g ask-cli-x".
##########################################################################
...
```
Major version update:
```
##########################################################################
[Info]: New MAJOR version (v0.12.0) of ask-cli-x is available now. Current version v-1.2.0.
It is recommended to use the latest version. Please update using "npm upgrade -g ask-cli-x".
##########################################################################
...
```

feat: add version reminder to high-level commands if ask-cli releases

---

lib/commands/smapi/cli-customization-processor.js
lib/commands/smapi/customizations/hook-functions/map-testers-emails.js
lib/commands/smapi/customizations/smapi-hooks.js
lib/commands/smapi/smapi-command-handler.js
lib/commands/smapi/smapi-commander.js
lib/utils/string-utils.js
package.json
test/unit/commands/smapi/cli-customization-processor-test.js
test/unit/commands/smapi/hook-functions/map-testers-emails-test.js
test/unit/commands/smapi/smapi-command-handler-test.js

the following command was failing before
`ask smapi list-catalogs-for-vendor`

fix: parse order of parameters from function source code

---

lib/commands/smapi/cli-customization-processor.js
lib/commands/smapi/smapi-command-handler.js
test/unit/commands/smapi/cli-customization-processor-test.js
test/unit/commands/smapi/smapi-command-handler-test.js
test/unit/commands/smapi/smapi-commander-test.js

The following commands were failing. 
ask smapi create-content-upload -c amzn1.ask-catalog.cat.c98f84ac-6730-4043-8fa7-19c93447f214 --number-of-upload-parts 1
ask smapi generate-catalog-upload-url -c amzn1.ask-catalog.cat.c98f84ac-6730-4043-8fa7-19c93447f214 --number-of-upload-parts 1
with error: class java.lang.String can not be converted to an Integer
--number-of-upload-parts had to be converted to number before sending to smapi.
this command was failing
ask smapi generate-credentials-for-alexa-hosted-skill -s amzn1.ask.skill.e9ac9d7f-5c4f-4c3b-8e41-1b347f625d95 --repository-url https://git-codecommit.us-east-1.amazonaws.com/v1/repos/e9ac9d7f-5c4f-4c3b-8e41-1b347f625d95 --repository-type GIT
url and type were overwriting each other instead of merging to the same object.
this PR fixes …

fix: parse to correct data type for nested body parameter

---

lib/commands/smapi/cli-customization-processor.js

Currently json and isArray can be applied together on a param like the example shown below:
```
$ ask smapi complete-catalog-upload -h
Usage: ask smapi complete-catalog-upload [options]
Completes an upload. To be called after the file is uploaded to the backend data store using presigned url(s).
Options:
-c,--catalog-id <catalog-id>  [REQUIRED] Unique identifier of the catalog
--upload-id <upload-id>       [REQUIRED] Unique identifier of the upload
--part-e-tags <part-e-tags>   [REQUIRED] List of (eTag, part number) pairs for each part of the file uploaded.
[MULTIPLE]: Values can be separated by comma.
[JSON]
-p, --profile <profile>       The ASK CLI profile to use. When you don't include this option, ASK CLI uses the default profile.
--debug                       When you include this …
```

fix: add logic to handle the param which isArray and isJson for smapi commands

---

lib/commands/smapi/cli-customization-processor.js
test/unit/commands/smapi/cli-customization-processor-test.js

fix when array property was displayed as json property
happened when array property is enum.
example:
`ask smapi set-subscription-for-development-events -h`
events should be [MULTIPLE] and not [JSON]

fix: fix when array property was displayed as json property

---

lib/utils/constants.js

adding missing subscriptions lwa scope.
discovered during writing integration tests.
can be reproduces by
`ask smapi list-subscribers-for-development-events`
should give
[Error]: {
"message": "User has not consented to this operation."
}
after running 
ask configure this error should disappear.

fix: add missing subscriptions lwa scope

---

bin/ask-smapi.js
lib/commands/smapi/smapi-command-handler.js
test/unit/commands/smapi/smapi-command-handler-test.js

Add additional debug output to smapi command. Added response headers, body and status code.
Example:
`ask smapi create-export-request-for-skill -s amzn1.ask.skill.e9ac9d7f-5c4f-4c3b-8e41-1b347f625d95 -g development --debug`
```
Operation: createExportRequestForSkillV1
Payload:
{
"skillId": "amzn1.ask.skill.e9ac9d7f-5c4f-4c3b-8e41-1b347f625d95",
"stage": "development"
}
Status code: 202
Response headers: [
{
"key": "content-type",
"value": "application/json"
},
{
"key": "content-length",
"value": "2"
},
{
"key": "connection",
"value": "close"
},
{
"key": "server",
"value": "Server"
},
{
"key": "date",
"value": "Tue, 28 Apr 2020 04:06:54 GMT"
},
{
"key": "x-amzn-requestid",
"value": "36c7742a-4577-47b3-b2ee-31f9e8ff9843"
},
{
"key": "x-amz-date",
"value": "Tue, 28 Apr 2020 04:06:54 GMT"
}, …
```

fix: add additional debug output to smapi commands

---

lib/commands/smapi/smapi-command-handler.js
lib/commands/smapi/smapi-commander.js
test/unit/commands/smapi/smapi-command-handler-test.js

Added option to read json from file path.
Examples:
```
ask smapi create-skill-for-vendor --manifest "$(cat skill-manifest.json)"
ask smapi create-skill-for-vendor --manifest file:skill-manifest.json
ask smapi create-skill-for-vendor --manifest file:/some-path/skill-manifest.json
```

feat: add option to read json from file path

---

lib/commands/option-model.json
lib/commands/smapi/appended-commands/get-task/index.js
lib/commands/smapi/appended-commands/search-task/index.js
lib/commands/smapi/smapi-commander.js
test/unit/commands/smapi/appended-commands/get-task/index-test.js
test/unit/commands/smapi/appended-commands/search-task/index-test.js
test/unit/run-test.js

examples:
```
ask smapi search-task -s amzn1.ask.skill.a27bf883-5903-4d5d-b2e0-9069fb54de6f --keywords "Test2,Test,TestPublicTask, lala"
ask smapi get-task -s amzn1.ask.skill.a27bf883-5903-4d5d-b2e0-9069fb54de6f --task-name amzn1.ask.skill.899a4901-0f83-4340-85b7-a941bfe3c73f.TestPublicTask --task-version 1
```

feat: add get and search task smapi commands

---

docs/concepts/New-Command.md
lib/commands/new/helper.js
lib/commands/new/index.js
lib/commands/new/wizard-helper.js
lib/commands/option-model.json
test/unit/commands/new/helper-test.js
test/unit/commands/new/index-test.js

add support for template-branch parameter in new command
Example:
```
ask new --template-url https://github.com/kakhaUrigashvili/skill-sample-nodejs-hello-world.git --template-branch develop
Please follow the wizard to start your Alexa skill project ->
? Choose a method to host your skill's backend resources:  AWS Lambda
Host your skill code on AWS Lambda (requires AWS account).
[Warn]: CLI is about to download the skill template from unofficial template https://github.com/kakhaUrigashvili/skill-sample-nodejs-hello-world.git. Please make sure you understand the source code to best protect yourself from malicious usage.
? Would you like to continue download the skill template?  Yes
? Please type in your skill name:  skill-sample-nodejs-hello-world
? Please type in your folder name for the …
```

feat: add support for template-branch parameter in new command

---

lib/clients/lwa-auth-code-client/index.js
lib/clients/smapi-client/index.js
lib/commands/configure/ask-profile-setup-helper.js
lib/commands/configure/index.js
lib/commands/new/hosted-skill-helper.js
lib/commands/smapi/smapi-command-handler.js
test/unit/clients/lwa-auth-code-client-test.js

This commit is to solve the error stack trace when users run `ask configure` but fail with the following message:
```
/ASK-CLI/lib/clients/lwa-auth-code-client/index.js:42
tokenBody.expires_at = this._getExpiresAt(tokenBody.expires_in).toISOString();
^
RangeError: Invalid time value
at Date.toISOString (<anonymous>)
at /ASK-CLI/lib/clients/lwa-auth-code-client/index.js:42:77
```
Now it fails with better message, and users are able to see full network activity using `--debug` for LWA requests.

fix: add error handling when refresh lwa token fails, pass in debug flag to all the authorizationController

---

package.json
test/integration/commands/smapi-commands-test.js
test/integration/fixtures/annotation-set.json

Update ask-smapi-models to add new commands
Added integration tests
New smapi commands:
```
create-nlu-evaluations
list-nlu-evaluations
get-nlu-evaluation
get-result-for-nlu-evaluations
create-nlu-annotation-set
list-nlu-annotation-sets
update-properties-for-nlu-annotation-sets
get-properties-for-nlu-annotation-sets
delete-properties-for-nlu-annotation-sets
update-annotations-for-nlu-annotation-sets
get-annotations-for-nlu-annotation-sets
```

feat: add annotation sets and evaluations commands

---

bin/ask-smapi.js

Currently if smapi-sdk fails with a certain setup (like Login with Amazon failure), it will throw error object which doesn't have "response" field. CLI will returns with: 
```
$ ask smapi get-vendor-list
(node:61479) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'constructor' of undefined
at Messenger.error (/Users/x/.nvm/versions/node/v10.8.0/lib/node_modules/ask-cli/lib/view/messenger.js:145:26)
...
(node:61479) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
After the change, it will show as 
```
$ ask smapi get-vendor-list
[Error]: {
"name": "AskSdkModelRuntime.DefaultApiClient Error"
}
```
And for other smapi api's …

fix: show full context if error happens, and don't fail smapi-sdk's error response

---

test/unit/utils/string-utils-test.js

Add a test case for stringUtils.
So the file's test coverage will be 100% :)
```bash
-----------------|----------|----------|----------|----------|-------------------|
File             |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-----------------|----------|----------|----------|----------|-------------------|
All files        |    95.68 |    93.85 |    95.18 |    95.72 |                   |
string-utils.js |      100 |      100 |      100 |      100 |                   |
...
```

test: add a test case of getParamNames function

---

lib/commands/deploy/index.js
lib/commands/init/helper.js
lib/commands/init/ui.js
lib/controllers/skill-code-controller/index.js
lib/model/resources-config/ask-resources.js
test/unit/commands/deploy/index-test.js
test/unit/commands/init/ui-test.js
test/unit/controller/skill-code-controller-test.js
test/unit/controller/skill-infrastructure-controller-test.js

The issues are related to the use case of ask-init with skillMetadata only. Supporting people who only wish to use ask-cli to deploy skill-package.
Originally, if users only do ask-init and use empty string for `Lambda code path`, they will see the following error which blocks their skill-package only settings:
```
? ask-resources.json already exists in current directory. Do you want to overwrite it?  Yes
? Skill Id (leave empty to create one):
? Skill package path:  ./skill-package
? Lambda code path (for default region):
[Error]: TypeError: Cannot read property 'type' of undefined
```
Even the ask-resources.json doesn't have code field, the deploy will still continue to try to deploy skill code:
```
$ ask deploy
Skill …
```

fix: allow ask init with only skillMetadata and fix NPEs during the flow

---

lib/builtins/deploy-delegates/cfn-deployer/assets/basic-lambda.yaml

Define a CloudWatch Logs LogGroup in the Skill's CloudFormation template.
We can easy to manage own Log Group.
For now, the Lambda function will create the functions LogGroup automatically.
But, the LogGroup has a several problems.
- The LogGroup does not delete when the CloudFormation deleted
- The LogGroup's retention in days is forever.
So if we create multiple skills by using the CLI, our AWS fee will be getting higher and higher by  LogGroup of these skills.
Because no LogGroup will be deleted without manual operation.
When we define the LogGroup Resource in our CloudFormation, we can easy to manage it!
We can update the log's retention days by updating the CloudFormation.
When we delete the skill, the CloudFormation will be delete the LogGroup automatically.
If we want to retain the …

feat: add a AWS:Logs:LogGroup Resource in cfn-deployer template

---

lib/commands/option-model.json
lib/commands/smapi/smapi-command-handler.js
lib/commands/smapi/smapi-commander.js
test/unit/commands/smapi/smapi-command-handler-test.js

adding full-response flag to smapi commands
Example:
`ask smapi get-skill-credentials -s amzn1.ask.skill.e9ac9d7f-5c4f-4c3b-8e41-1b347f625d95 --full-response`

feat: add full-response flag to smapi commands

---

lib/commands/abstract-command.js
test/unit/commands/abstract-command-test.js

Addressing https://github.com/alexa/ask-cli/issues/193
http client should reject on bad status code.
for example this how axios behaves.
https://github.com/axios/axios
Side Note: Request lib is deprecated https://www.npmjs.com/package/request

fix: add behaviour to http client to reject on bad http status codes

---

lib/commands/smapi/cli-customization-processor.js
test/unit/commands/smapi/cli-customization-processor-test.js

required will be determined as the following
1) if parent has required array and the child key is in the array then true else false
2) else if parent does not have required array then inherit require from parent.
Step 2: Update swagger to make sure lower leafs have required defined to fix some minor inconsistencies.

fix: smapi - improve logic to determine required for nested body params

---

lib/builtins/deploy-delegates/cfn-deployer/index.js
lib/builtins/deploy-delegates/lambda-deployer/helper.js
lib/builtins/deploy-delegates/lambda-deployer/index.js
lib/controllers/skill-infrastructure-controller/index.js
lib/view/multi-tasks-view.js
test/unit/builtins/lambda-deployer/helper-test.js
test/unit/builtins/lambda-deployer/index-test.js
test/unit/controller/skill-infrastructure-controller-test.js
test/unit/view/multi-tasks-view-test.js

This fix solves issue https://github.com/alexa/ask-cli/issues/162.
It also cleans the logic for the response of `invoke` method for each deployer:
```
function invoke(..., callback) {
* callback satisfies the structure of { errorStr, responseObj }
*   .errorStr     deployDelegate will fail immediately with this errorStr
*   .responseObject.isAllStepSuccess: show if the entire process succeeds
*   .responseObject.isCodeDeployed: true if the code is uploaded sucessfully and no need to upload again
*   .responseObject.deployState: record the state of deployment back to file (including partial success)
*   .responseObject.endpoint: the final result endpoint response
*   .responseObject.resultMessage: the message to summarize current situation
}
```

feat: support partial deploy for lambda-deployer and revisit the protocol for deployer response

---

lib/clients/git-client.js
lib/controllers/hosted-skill-controller/clone-flow.js
test/unit/clients/git-client-test.js

before credential helper was applied to all remotes in the repo.
this would not allow developers to use git to push to their repo if they used hosted skill.
scoped credential helper to hosted skill repo only.
before config looked like this
`cat .git/config`
```
[credential]
helper = 
helper = ask configure util git-credentials-helper
UseHttpPath = true
```
after:
```
[credential "https://git-codecommit.us-east-1.amazonaws.com/v1/repos/da0f45e9-8931-40d1-942a-bce471b1fc55"]
helper = 
helper = !ask util git-credentials-helper --profile default
UseHttpPath = true
```
You can test by adding second remote and pushing to it
```
git remote add personal git@github.com:kakhaUrigashvili/alexa-hosted-skill.git
git push personal master
```

fix: add host url to apply credential helper to hosted skill repo only

---

lib/commands/smapi/smapi-command-handler.js
lib/utils/string-utils.js
test/unit/commands/smapi/smapi-command-handler-test.js
test/unit/utils/string-utils-test.js

trying to test with
```
ask smapi update-annotations-for-nlu-annotation-sets -s amzn1.ask.skill.e9ac9d7f-5c4f-4c3b-8e41-1b347f625d95 --annotation-id 0ed2ab5f-8b1b-423e-995c-1381d14cd496 --content-type text/csv --update-nlu-annotation-set-annotations-request file:fixtures/annotation-set.csv
```
but getting
```
"response": {
"message": "Validation error: Could not process Annotation Set content with format text/csv for the following reason: (line 1) invalid char between encapsulated token and delimiter.."
}
```
my csv file
```
"utterance","referenceTimestamp","intent","slot[toCity]","slot[fromCity]","slot[travelDate]"
"plan a trip","","PlanMyTripIntent","","",""
```

feat: add support for csv content type body param in smapi

---

lib/commands/smapi/smapi-command-handler.js
lib/commands/smapi/smapi-commander.js
test/unit/commands/smapi/smapi-command-handler-test.js

adding support for non json response.
Need to wait until ask-smapi-sdk also fixes this issue.
example command with non json response
`ask smapi get-annotations-for-nlu-annotation-sets -s amzn1.ask.skill.e9ac9d7f-5c4f-4c3b-8e41-1b347f625d95 --annotation-id 0ed2ab5f-8b1b-423e-995c-1381d14cd496 --accept text/csv`

Parse csv fix

---

docs/concepts/Dialog-Command.md
lib/commands/dialog/index.js
test/unit/commands/dialog/index-test.js

addressing issue from https://github.com/alexa/ask-cli/issues/220

fix: read first locale from skill.json if not provided by user

---

package.json

Sometimes( may be once in 2-3 weeks), unit test will fail with the following error
1) Command test - AbstractCommand class # check AppConfig object  | should not be null for non-configure commands:
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
at listOnTimeout (internal/timers.js:531:17)
at processTimers (internal/timers.js:475:7)
2) Command test - AbstractCommand class # check AppConfig object  | should be null for configure command:
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
at listOnTimeout (internal/timers.js:531:17)
at processTimers (internal/timers.js:475:7)
I tried adding done but get this following error …

test: increase timeout to fix sporadic test timeout error

---

lib/builtins/deploy-delegates/cfn-deployer/helper.js
lib/clients/aws-client/cloudformation-client.js
test/unit/clients/aws-client/cloudformation-client-test.js

Addressing issue
https://github.com/alexa/ask-cli/issues/210

fix: add logic to create stack if old stack in delete complete status

---

lib/commands/dialog/index.js
test/unit/commands/dialog/index-test.js

Since we dont have 
```
"skillMetadata": {
"src": "./skill-package"
},
```
for hosted skill. dialog command would not work without providing skill id similar to other types of skills (lambda and cf).
Updated to default to skill-package to allow working with hosted skills.

fix: fix to allow dialog without providing skill id for hosted skills

---

lib/builtins/deploy-delegates/lambda-deployer/helper.js
lib/builtins/deploy-delegates/lambda-deployer/index.js
lib/commands/deploy/helper.js
lib/commands/deploy/index.js
lib/controllers/skill-infrastructure-controller/index.js
test/unit/builtins/lambda-deployer/helper-test.js
test/unit/builtins/lambda-deployer/index-test.js
test/unit/commands/deploy/helper-test.js
test/unit/commands/deploy/index-test.js

--ignore-hash option not implemented
Deploy command updated to support the ignoreHash option.
The deploySkillInfrastructure helper command now accepts an ignoreHash parameter alongside profile and debug.
The builtin lambda-deployer validateLambdaDeployState method supports an ignoreHash parameter.
All tests use the TEST_IGNORE_HASH default.

Ignore hash flag

---

lib/commands/smapi/smapi-commander.js

Adding default value of development for stage when stage is required.
example
```
Options:
-s,--skill-id <skill-id>         [REQUIRED] The skill ID.
-g,--stage <stage>               [REQUIRED] Stage for skill. (default: "development")
```
still kept it required but added default value.

feat: add default value development when stage is required

---

lib/commands/smapi/smapi-command-handler.js
test/integration/commands/smapi-commands-test.js
test/unit/commands/smapi/smapi-command-handler-test.js

fixing 2 minor issues
1) passing profile to status hint if it was provided for the command
2) fixing to pass correct parameter name if it was customized. for example: stageV2 should be state.

fix: pass profile to status hint; handle customized param names

---

lib/view/multi-tasks-view.js
test/unit/view/multi-tasks-view-test.js

Steps to reproduce
1) update ~/.aws/credentials and put invalid aws_secret_access_key
2) ask deploy with lambda deployer
the deploy will hang on creating IAM role step
This PR make sure the error gets propagates and fail the command.

fix: output deploy error if error not string

---

lib/commands/deploy/index.js
lib/controllers/skill-metadata-controller/index.js
test/unit/commands/deploy/index-test.js
test/unit/controller/skill-metadata-controller-test.js

Addresses https://github.com/alexa/ask-cli/issues/214
```
$ ask deploy
Skill package deployed successfully.
...
==================== Enable Skill ====================
[Warn]: CliWarn: Skill with multiple api domains cannot be enabled. Skip the enable process.
$ echo $?
0
```

fix: do not throw error exit code when the enable-skill request skipped

---

lib/commands/new/ui.js
test/unit/commands/new/ui-test.js

When the terminal is not wide enough this will happen when moving the cursor:
```
$ ask new
Please follow the wizard to start your Alexa skill project ->
? Choose the programming language you will use to code your skill:  NodeJS
? Choose a method to host your skill's backend resources:  AWS with CloudFormation
Host your skill code with AWS services and provision with AWS CloudFormation (requires AWS account)
? Choose a template to start with:  (Use arrow keys)
❯ Hello world		    Alexa's hello world skill to send the greetings to the world!
? Choose a template to start with:
Hello world		    Alexa's hello world skill to send the greetings to the world!
? Choose a template to start with:
Hello world		    Alexa's hello world skill to send the greetings to the world!
? Choose a template to …
```

fix: add pageSize to avoid the description of the template gets too long and breaks the line

---

lib/builtins/deploy-delegates/cfn-deployer/helper.js
lib/builtins/deploy-delegates/lambda-deployer/index.js

This change of default AWS region is based on the smartHome skill developers' feedback. Our documentation shows us-west-2 is the optimal AWS region for FE endpoint:
https://developer.amazon.com/en-US/docs/alexa/smarthome/develop-smart-home-skills-in-multiple-languages.html#deploy
https://developer.amazon.com/en-US/docs/alexa/custom-skills/host-a-custom-skill-as-an-aws-lambda-function.html#allowed-regions

feat: modify the default AWS region for FE to us-west-2

---

lib/commands/smapi/smapi-commander.js

Issue: developers from Windows cannot use "$cat" command, suggest them using "type" command in the option's description, plus some rephasing. 
Preview of the result (check --manifest option):
```
$ ask smapi update-skill-manifest -h
Usage: ask smapi update-skill-manifest [options]
Updates skill manifest for given skillId and stage.
Options:
--if-match <if-match>     [OPTIONAL] Request header that specified an entity tag. The server will update the resource only if the eTag matches with the resource's current
eTag.
-s,--skill-id <skill-id>  [REQUIRED] The skill ID.
-g,--stage <stage>        [OPTIONAL] Stages of a skill including the new certified stage.
* `development` - skills which are currently in development corresponds to this stage.
* `certified` -  skills which have completed …
```

fix: improve the description for ask-smapi command [JSON] options

---

lib/builtins/deploy-delegates/lambda-deployer/helper.js
lib/view/multi-tasks-view.js
test/unit/builtins/lambda-deployer/helper-test.js
test/unit/view/multi-tasks-view-test.js

Fixing issue when "[Error]: object Object” is thrown during deploy to show more meaningful error message.
Reproduce:
1) ask deploy with lambda deployer
2) remove lambda:UpdateFunctionConfiguration permission
3) change something in .ask/ask-states.json (for example skillId)
4) ask deploy or ask deploy --ignore-hash.

fix: error object Object to show meaningful error message

---

lib/clients/smapi-client/resources/alexa-hosted.js
lib/commands/new/hosted-skill-helper.js
lib/commands/new/ui.js
lib/commands/new/wizard-helper.js
lib/controllers/hosted-skill-controller/index.js
lib/utils/constants.js
test/functional/commands/high-level-commands-test.js
test/unit/clients/smapi-client-test/resources/alexa-hosted.js
test/unit/commands/new/ui-test.js
test/unit/commands/new/wizard-helper-test.js

add locale and region to ask new for hosted skill

feat: add locale and region for AHS

---

.github/workflows/functional-test.yml

Add DEBUG flag so we see why func test for hosted skill times out sometimes.

chore: add DEBUG to functional test

---

lib/builtins/deploy-delegates/cfn-deployer/index.js

fix to always store template path in posix style in ask-resources.json
"templatePath": "./infrastructure/cfn-deployer/skill-stack.yaml"
it works both on windows and mac  when running fs.readFileSync(templatePath, 'utf-8')

fix: issue with different path on windows and mac

---

lib/clients/lwa-auth-code-client/index.js

```ask util generate-lwa-tokens```
When generating lwa-tokens. In case of the invalid client. `tokenBody.expires_in` will be undefined which causes `RangeError: Invalid time`. 
So here legit error is thrown back in case of an invalid client.

Log error on auth failure.

---

lib/clients/smapi-client/resources/catalog.js
test/unit/clients/smapi-client-test/resources/catalog.js

Fix the failure in the `ask smapi upload-catalog` command when multi-parts upload happens

fix: failure in smapiClient for createCatalogUpload method

---

.github/workflows/functional-test.yml

skipping functional test on master branch for release commit to prevent duplicate run during the release.

chore: skip release commit on master branch from github actions

---

lib/commands/deploy/helper.js
lib/commands/deploy/index.js
lib/utils/profile-helper.js
lib/view/messenger.js
test/unit/commands/configure/index-test.js
test/unit/commands/deploy/helper-test.js
test/unit/commands/deploy/index-test.js

Happy case
```
$ ask deploy
Deploy configuration loaded from ask-resources.json
Deploy project for profile [default]
...
```
Profile mismatch
```
$ ask deploy -p prod
Deploy configuration loaded from ask-resources.json
[Error]: Profile [prod] does not exist. Please configure it in your ask-resources.json file.
```
Profile doesn't exist
```
$ ask deploy -p def
[Error]: Can't resolve profile [def] as it doesn't exist. Please run "ask configure --profile def" first.
```
This addresses https://github.com/alexa/ask-cli/issues/293

fix: add profile checker in the deploy flow

---

docs/concepts/Deploy-Command.md
lib/builtins/deploy-delegates/lambda-deployer/helper.js
lib/builtins/deploy-delegates/lambda-deployer/index.js
test/unit/builtins/lambda-deployer/helper-test.js
test/unit/builtins/lambda-deployer/index-test.js

This commit addresses the feature requests from https://github.com/alexa/ask-cli/issues/166 and the partial feature request from https://github.com/alexa/ask-cli/issues/283.
Introduce `userConfig.basedOn` into the skillInfrastructure JSON object in ask-resources.json. User can provide `basedOn.lambda.arn` to let ask-cli target the deployment to the existing Lambda ARN.
```JSON
{
"skillInfrastructure":{
"userConfig":{
"basedOn":{
"lambda":{
"arn":"arn:aws:lambda:us-east-1:12345:function:ask-function"
}
},
"runtime":"nodejs10.x",
"handler":"index.handler",
"awsRegion":"us-east-1",
"regionalOverrides":{
"FE":{
"basedOn":{
"lambda":{
"arn":"arn:aws:lambda:us-west-2:12345:function:ask-function"
}
}
}
}
},
"type":"@ask-cli/lambda-deployer"
}
}
```
1. When setting `basedOn.lambda.arn = …

feat: support sourceLambda field for lambda-deployer to use existing Lambda

---

lib/commands/smapi/smapi-command-handler.js
lib/view/json-view.js
test/unit/commands/smapi/smapi-command-handler-test.js

1) fixing outputting error instead of {}. happens when ask smapi model throws unexpected error. for example the api endpoint is not available.
2) by default sending at least {} for body param to fix potential edge case when body param is required but all props inside of it are not required.

fix: smapi - pass {} by default when non of the in body params specified

---

lib/clients/http-client.js
lib/commands/smapi/smapi-command-handler.js
lib/utils/dynamic-config.js

append custom user agent string to smapi client

fix: append custom user agent string to smapi client

---

lib/clients/aws-client/lambda-client.js

fix when profile name is too long. it breaks deploy when generated lambda name is too long. cherry picked from https://github.com/alexa/ask-cli/pull/245

fix: shorten profile name lambda function name generation

---

.babelrc.js
.npmignore
package.json

Fixing issue to allow installing ask cli as local dependency
Right before npm publish we will run babel to replace module aliases. Using prepublishOnly hook
https://docs.npmjs.com/cli/v6/using-npm/scripts
Testing
1) Changed name in package.json and publish my personal package
2) Installed locally and verified that it works with something like that "npm run ask -- new"
3) installed globally and verified that it still works as global dependency.

add: module resolve

---

lib/view/json-view.js

Fixing issue when some of the error properties are not shown when outputting error to console.
example 
`ask smapi update-skill-manifest -s amzn1.ask.skill.fcb348d9-a177-4891-8e43-5a10d30e3e38 -g development --manifest file:TestSkill.json `
TestSkill.json has properties that violate server side validation.
Before
```
[Error]: {
"message": "Server cannot process the request due to a client error.",
"stack": "ServiceError: Server cannot process the request due to a client error.\n    at SkillManagementServiceClient.<anonymous> (/Users/kakuri/Git/ask-cli-v2/node_modules/ask-sdk-model-runtime/dist/index.js:335:31)\n    at step (/Users/kakuri/Git/ask-cli-v2/node_modules/ask-sdk-model-runtime/dist/index.js:58:23)\n    at Object.next (/Users/kakuri/Git/ask-cli-v2/node_modules/ask-sdk-model-runtim …
```

fix: display all property when printing error

---

docs/concepts/Alexa-Skill-Project-Definition.md
lib/builtins/deploy-delegates/cfn-deployer/assets/basic-lambda.yaml
lib/builtins/deploy-delegates/lambda-deployer/helper.js
lib/clients/aws-client/lambda-client.js
lib/controllers/skill-infrastructure-controller/index.js
lib/model/manifest.js
lib/model/resources-config/ask-resources.js
lib/model/resources-config/index.js
test/unit/builtins/lambda-deployer/helper-test.js
test/unit/clients/aws-client/lambda-client-test.js
test/unit/controller/skill-infrastructure-controller-test.js
test/unit/fixture/model/manifest.json
test/unit/fixture/model/regular-proj/ask-resources-min.json
test/unit/fixture/model/regular-proj/ask-resources.json

add targetEndpoint property to ask-resources.json.
Tested with CFN and Lambda deployer. If lambda/skill already exists, the permission for new skill type (smart home for example) need to be added manually. If creating fresh, it should all work.
Test
"targetEndpoint": ["custom","smartHome", "events"]
CF Deployer
```
ask deploy
Deploy configuration loaded from ask-resources.json
Deploy project for profile [default]
[Warn]: The hash of current skill package folder does not change compared to the last deploy hash result, CLI will skip the deploy of skill package.
Skill ID: amzn1.ask.skill.4f5eecb6-1069-4bb4-9299-927f213c30fd
==================== Build Skill Code ====================
Skill code built successfully.
Code for region …
```

feat: add targetEndpoint property to ask-resources.json

---

lib/model/abstract-config-file.js
lib/model/resources-config/ask-resources.js
test/unit/commands/deploy/index-test.js
test/unit/commands/new/helper-test.js

Addressing https://github.com/alexa/ask-cli/issues/348
Adding additional info to the error message
Before
```
ask deploy
[Warn]: File /Users/kakuri/test/lmtest/ask-resources.json not exists.
```
After
```
ask deploy
[Warn]: File /Users/kakuri/test/lmtest/ask-resources.json not exists. If this is a skill project managed by v1 ask-cli, please run 'ask util upgrade-project' then try the command again.
```

chore: improve error message when config file is not found

---

lib/commands/dialog/index.js
lib/commands/option-model.json
lib/controllers/dialog-controller/index.js
lib/model/dialog-replay-file.js
test/unit/commands/dialog/index-test.js
test/unit/controller/dialog-controller/index-test.js
test/unit/model/dialog-replay-file-test.js

Addressing https://github.com/alexa/ask-cli/issues/347 and doing additional clean up
1) minor formatting change for some options descriptions
2) removing restriction for replay file to have .json extension
3) removed code to read/ write yml replay file, since it was not possible due to our validations.
test non exisiting file
```
ask dialog -r not-existing
[Error]: Failed to parse file: not-existing.
File not-existing not exists.
```
test non json file
```
ask dialog -r out
[Error]: Failed to parse file: out.
out: Unexpected string in JSON at position 166
```
test good file
```
ask dialog -r out
========================================================== Welcome to ASK Dialog ==========================================================
========================================= Replaying a …
```

fix: removing restriction for replay file to have .json extension

---

bin/ask.js
docs/concepts/Run-Command.md
lib/commands/option-model.json
lib/commands/run/helper.js
lib/commands/run/index.js
lib/commands/run/run-flow/abstract-run-flow.js
lib/commands/run/run-flow/java-run.js
lib/commands/run/run-flow/nodejs-run.js
lib/commands/run/run-flow/python-run.js
lib/utils/constants.js
package.json
test/unit/commands/run/helper-test.js
test/unit/commands/run/index-test.js
test/unit/commands/run/run-flow/java-run-test.js
test/unit/commands/run/run-flow/nodejs-run-test.js
test/unit/commands/run/run-flow/python-run-test.js
test/unit/run-test.js

*Adding support to initiate local debugging process from the ASK CLI. *
1. Functionality will be support for Node, Python and Java skills.  Support for both hosted and non-hosted skill variant are provided. Works for non-hosted skills as long as the `ask-resources.json` contains the necessary info - skill id, skill code folder, runtime and handler name.
2. The feature also comes equipped with nodemon that restarts the debugging process when files in the workspace are modified. This is available for all 3 languages.
3. The user will be expected to add the `ask-sdk-local-debug` dependencies on to their skill code.
4. For Python, inorder to support attachment on an inspector, a debugger provided by microsoft - [`debugpy`](https://github.com/microsoft/debugpy) is used. 
**Using the command** …

feat: local debugging support with file watcher

---

docs/concepts/Configure-Command.md
lib/utils/constants.js

Lambda will deprecate two managed policies called "AWSLambdaFullAccess" and "AWSLambdaReadOnlyAccess" on January 25, 2021.
new scoped down policies called "AWSLambda_FullAccess" and "AWSLambda_ReadOnlyAccess"

chore: change lambda policy to AWSLambda_FullAccess

---

lib/clients/aws-client/lambda-client.js

Addressing https://github.com/alexa/ask-cli/issues/370
increase lambda default memory and timeout to match CF deployer default settings.
Only change for on initial creation of lambda.

fix: increase lambda default memory and timeout

---

lib/controllers/skill-metadata-controller/index.js
lib/utils/zip-utils.js
test/unit/controller/skill-metadata-controller-test.js
test/unit/utils/zip-utils-test.js

There's a new extension feature skill-package validator, which is a fileSystemWatcher on skilPackage folder. If the watcher catch any unexecpeted files, it will throw warn in the extension. 
Recently there's customer tried to use the cli to deploy skill with the extension opened. Since the cli will generate the temp zip under skillPackage, it will trigger the extension alert. 
Instead of generating the zip file under skillPackage folder, rightnow will move the temp zip to .ask folder.
Changed the zipUtil.createTempZip function to take in a new param which will specify the output dir. And in the skillDeployController, add logic to get the .ask folder path and pass it into the createTempZip.
Fixed all the unit tests. And tested this feature …

fix: move the temp zip file to .ask to integ with extension

---

lib/clients/aws-client/iam-client.js

**Issue**: If a user used the lambda option to host their skill and their skill name was >39 characters it would throw an error when running the `ask deploy` command, since the lambda role name can currently only be <=64 characters.
**Fix Description**: Truncating the skill name for lambda role creation (It truncates the skill name if the skill name is >39 characters.)
**Before the change**: 
`[Error]: CliError: Failed to create IAM role before deploying Lambda. ValidationError: 1 validation error detected: Value 'ask-lambda-python-alexa-skill-starter-template-cli-v2-1614216403551' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64`
**After the change**:
`arn:aws:iam::453667022293:role/ask-lambda-python-alexa-skill-starter-template-cl-1614216451762 …

fix(lambda): truncating the skill name for lambda role creation

---

lib/commands/smapi/appended-commands/export-package/index.js
lib/controllers/hosted-skill-controller/index.js
lib/controllers/skill-metadata-controller/index.js
lib/utils/constants.js
test/integration/commands/smapi-commands-test.js
test/integration/fixtures/skill-manifest.json
test/unit/clients/smapi-client-test/resources/alexa-hosted.js

This change allows the usage of Node.js 12 for Alexa Hosted Skills creation.

feat: Change Alexa Hosted Skill runtime to Node.js 12

---

lib/commands/dialog/index.js
test/unit/commands/dialog/index-test.js

This solves the issue https://github.com/alexa/ask-cli/issues/405
Before
```
$ ask dialog
Defaulting locale to the first value from the skill manifest: en-US
...
User  > open pizza reference
[Error]: {
"message": "Invalid request payload. Please ensure that the request payload has no invalid fields"
}
User  >
```
AFter the fix:
```
$ ask dialog
Defaulting locale to the first value from the skill manifest: en-US
...
User  > open pizza reference
Alexa > Welcome.
```

fix: do not set DEFAULT to simulation.type when making simulate-skill request

---

lib/builtins/build-flows/python-pip.js
lib/builtins/deploy-delegates/lambda-deployer/helper.js
lib/utils/constants.js
test/unit/builtins/build-flows/python-pip-test.js
test/unit/builtins/lambda-deployer/helper-test.js

Issue #, if available:
Fixes: #415 
This change adds waiting for Lambda function state updates support which is now required per [this blog post](https://aws.amazon.com/de/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions). The `lambda-deployer` workflow will now wait after each Lambda function operations (create, add event permission, update code and update configuration) while the function state and last update status are pending/in progress. Once these properties are available, the deployment workflow will only continue if the function state is `Active` and the last update status is `Successful`.
A fix for the Windows test integration is also included. The Windows image now runs Python 3.10 which is breaking the Python build flow as it …

fix: wait for lambda function state updates

---

lib/builtins/build-flows/nodejs-npm.js
test/unit/builtins/build-flows/nodejs-npm-test.js

This change fixes the misspelling of the `quiet` flag for the `npm install` command.

fix: use proper npm install quiet flag

---

lib/utils/constants.js

npm has [announced](https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/) that they will be deprecating non-HTTPS access on October 4, 2021. This change updates the npm registry base url to use https.

fix: use npm registry https url

---

docs/concepts/Deployer-CFN-Deployer.md
lib/builtins/deploy-delegates/cfn-deployer/helper.js
lib/builtins/deploy-delegates/cfn-deployer/index.js
lib/controllers/skill-infrastructure-controller/index.js
test/unit/builtins/cfn-deployer/helper-test.js
test/unit/builtins/cfn-deployer/index-test.js

This change adds optional skill credentials `SkillClientId` & `SkillClientSecret` parameters support to `cfn-deployer` stack templates. If specified, the value of these parameters is directly retrieved from SMAPI based on the skill ID.
This is useful for including that information as environmental variables of a deployed Lambda function handling skill messaging events.

feat: add cfn deployer skill credentials parameters

---

docs/concepts/Alexa-Skill-Project-Definition.md
lib/controllers/skill-infrastructure-controller/index.js
lib/model/manifest.js
lib/model/resources-config/ask-resources.js
lib/model/resources-config/index.js
test/unit/controller/skill-infrastructure-controller-test.js
test/unit/fixture/model/regular-proj/ask-resources.json

Fixes: #47 
This change adds the ability to customize the events property of the skill manifest when the deployed Lambda function can handle these events.
The original support for "events" via the `targetEndpoint` property was replaced by the new `skillEvents` property since the previous implementation to add skill events support wasn't useable out of the box.
The documentation was updated and includes some minor cleanup.
```
{
"askcliResourcesVersion": "2020-03-31",
"profiles": {
"default": {
"skillMetadata": {
"src": "./skill-package"
},
"code": {
"default": {
"src": "./lambda"
}
},
"skillInfrastructure": {
"type": "@ask-cli/lambda-deployer",
"userConfig": {
"runtime": "nodejs12.x",
"handler": "index.handler",
"skillEvents": { …
```

feat: add skill events property to ask-resources.json

---

docs/concepts/Deploy-Command.md
lib/builtins/deploy-delegates/lambda-deployer/helper.js
lib/clients/aws-client/iam-client.js
lib/clients/aws-client/lambda-client.js
lib/utils/constants.js
test/unit/builtins/lambda-deployer/helper-test.js
test/unit/clients/aws-client/iam-client-test.js
test/unit/clients/aws-client/lambda-client-test.js

This change adds the ability to customize some additional Lambda function config parameters (function name, description, memory size, timeout and environmental variables) through the ask resources user config, when using the Lambda deployer. This is useful if a user only needs to deploy a Lambda function part of the skill stack without the need to use the CFN deployer just to set this customization.
Some minor code refactoring and cleanup is included mostly moving the generate AWS resource name functions out of the clients library into the relevant builtins instead.
```
{
"askcliResourcesVersion": "2020-03-31",
"profiles": {
"default": {
"skillMetadata": {
"src": "./skill-package"
},
"code": {
"default": {
"src": "./lambda"
}
},
"skillInfrastructure": {
"type": …
```

feat: add lambda deployer additional user config function parameters

---

lib/commands/new/index.js
lib/utils/constants.js
test/unit/commands/new/index-test.js

#393 
Updating the documentation link that is displayed after `ask new` with an Alexa hosted skill. The current link navigates to Alexa hosted skill docs that aren't relevant to the CLI. The new link navigates to CLI related docs for hosted skills.

chore: updated hosted skill documentation link

---

lib/builtins/deploy-delegates/cfn-deployer/index.js
lib/builtins/deploy-delegates/lambda-deployer/index.js
lib/controllers/skill-infrastructure-controller/index.js
lib/view/multi-tasks-view.js
test/unit/builtins/cfn-deployer/index-test.js
test/unit/builtins/lambda-deployer/index-test.js
test/unit/controller/skill-infrastructure-controller-test.js
test/unit/view/multi-tasks-view-test.js

Fixes: #388
This change limits the skill infrastructure deployment to one task per AWS region by skipping the additional task(s) and copying the deploy state of the first task deployed in the same region. This will prevent unnecessary resources from being deployed twice in the same region and more importantly allow non-unique resource names configured in the stack template to be used on a per region basis.
The task skip implementation is taking advantage of the `listr` skip function. The change also includes a fix to ensure that previous Lambda deploy states are kept in the ask states file after getting an error. A basic use case of a revision id mismatch would currently reset that information making the subsequent call recreate …

fix: limit skill infrastructure deployment to one task per aws region
